Repository Dev-CasperTheGhost/ghostybot, pull requests merged in 2020-10, with the labels that each got.

#34 updated kick, ban, mute, addrole, removerole command
  src/commands/admin/addrole.js
  src/commands/admin/ban.js
  src/commands/admin/kick.js
  src/commands/admin/mute.js
  src/commands/admin/removerole.js
Labels: hacktoberfest

#36 Welcome card, goodbye card
  package.json
  src/events/guildMemberAdd.js
  src/events/guildMemberRemove.js
Labels: hacktoberfest

#37 IMDB Information
  config.example.json
  package.json
  src/commands/util/imdb.js
Labels: hacktoberfest

#48 Create feed.js
  src/commands/image/feed.js
Labels: hacktoberfest

#49 text to image maker
  src/commands/image/imgfy.js
Labels: hacktoberfest

#59 Create amazeme.js
  src/commands/image/amazeme.js
Labels: hacktoberfest

#62 creatted addroleall.js & removeroleall.js
  src/commands/admin/addroleall.js
  src/commands/admin/removeroleall.js
Labels: hacktoberfest

#64 Logging with webhooks 🥳
  src/commands/admin/set.js
  src/commands/admin/unset.js
  src/commands/economy/moneyleaderboard.js
  src/events/channelCreate.js
  src/events/channelDelete.js
  src/events/channelUpdate.js
  src/events/emojiCreate.js
  src/events/emojiDelete.js
  src/events/emojiUpdate.js
  src/events/guildMemberUpdate.js
  src/events/messageDelete.js
  src/events/messageUpdate.js
  src/events/roleCreate.js
  src/events/roleDelete.js
  src/events/roleUpdate.js
  src/utils/functions.js
Labels: hacktoberfest

#74 Update skin.js
  src/commands/util/skin.js
Labels: bug-fix

#66 Updated play.js & nowplaying.js
  package.json
  src/commands/music/nowplaying.js
  src/commands/music/play.js
Labels: enhancement

#81 🎉 Update APIS USED
  docs/APIS_USED.md
Labels: documentation
